# taps
tap 'dimentium/autoraise'

# CLI ツール
# brew 'aicommit'
brew 'asdf'
brew 'awscli'
brew 'chezmoi'
brew 'direnv'
# brew 'dolt'
# brew 'ffmpeg'
# brew 'firebase-cli'
brew 'fzf'
brew 'gh'
brew 'ghq'
brew 'git'
# brew 'grpcurl'
# brew 'imagemagick'
brew 'jq'
# brew 'leptonica'
# brew 'libtasn1'
brew 'mise'
brew 'mysql'
# brew 'ollama'
# brew 'p11-kit'
# brew 'plantuml'
# brew 'pnpm'
brew 'rbenv'
brew 'rtk'
# brew 'rust'
# brew 'rustup'
brew 'sheldon'
brew 'tig'
# brew 'tmux'
brew 'tree'
brew 'typos-cli'
brew 'watch'
brew 'watchman'
brew 'yarn'

# GUI アプリ
# cask '1password'
# cask 'bitwarden'
# cask 'android-studio'
# cask 'applite'
cask 'claude'
cask 'claude-code'
# cask 'clipy'
cask 'codex'
cask 'codex-app'
cask 'cursor'
cask 'docker-desktop'
# cask 'entire'
# cask 'figma'
cask 'firefox'
# cask 'ghostty'
# cask 'gimp'
# cask 'brave-browser'
# cask 'google-chrome'
cask 'thebrowsercompany-dia'
cask 'iterm2'
# cask 'mac-mouse-fix'
# cask 'openclaw'
# cask 'insomnia'
cask 'postman'
cask 'tableplus'
cask 'raycast'
cask 'slack'
# cask 'visual-studio-code'
# cask 'warp'
cask 'zoom'
